---
line_width: 0.6
font_size: 9
title_font_size: 9
font_family: serif
math_font_family: dejavuserif
fig_size_x: 9
fig_size_y: 5
x_label: Wavelength in Å
y_label: Relative intensity
no_grid: 0
object_name: 
title_pattern: "- %%DATE-OBS%% - %%EXPTIME2%% - %%BSS_SITE%% - %%OBSERVER%%"
label_pattern: "%%DATE-OBS%%"
subtitle_pattern: "%%BSS_INST%%"
spec_file_regex: '_(.+)_(\d+)_(\d+)(.*).fit'
2D_spectrum_display: 0
2D_spectrum_postfix: '_2D.fits'
2D_spectrum_posy:
2D_spectrum_height: 
2D_spectrum_cmap: gray
crop: 0
compare_mode : 0
compare_mode_y_offset : 0
compare_mode_color: 
compare_mode_no_label: 0
dpi: 150
lines_display_name: 0
lines_color: red
lines: 
  # line name, position in angstroms, offset x, offset y
  # line name, position in angstroms, offset x, offset y
  #- Ca II K,3933.68,-4,1.5
  #- Ca II H,3968.49,-4,1.5
  #- Hα,6562.82,6.,0.3
  #- Hβ,4861.35,6.,0.3
  #- Hγ,4340.47,6.,0.3
  #- Hδ,4101.73,6.,0.3
  #- Hε,3970.07,6.,0.3
  #- Hζ,3889.06,6.,0.3
  #- Hη,3835.397,4.,0.3
  #- He II,4541.59,4.,0.3
  #- C III,4647.00,4.,0.3
  #- He II,4685.68,4.,0.3
  #- He I,4921.93,4.,0.3
  #- He I,5015.68,4.,0.3
  #- He II,5411.52,4.,0.3
  #- He I,5875.65,4.,0.3
  #- He I,6678.15,4.,0.3
  #- He I, 7065.30,6.,0.3